### PR TITLE
Adding equivalence for EBMS Redbee

### PR DESCRIPTION
**Pull request by timothy22000**

### CODE REVIEW

**Comment by Dalamar42** [comment]
Are you sure you want the repetition for this one to NEVER?

**Comment by timothy22000** [comment]
hmm, I am following the other VF equivalence updaters. I think there was a reason why they were NEVER, to show equivalence before and after in the schedule EPG?

**Comment by Dalamar42** [comment]
This means it will never run though unless someone triggers it. Are we ok with that?

**Comment by timothy22000** [comment]
I'll check with Chris and update my PR if it is required :)

**Pull request merged**
